@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{baseUrl}}/sessions/login
Content-Type: application/json

{
  "cpf": "000000001",
  "password": "123456"
}

###

# @name create_deliveryman
POST {{baseUrl}}/accounts/deliveryman
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "John Doe",
  "cpf": "00000000005",
  "password": "123456",
  "role": "MEMBER"
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "john doe",
  "street": "z.string()",
  "complement": "z.string()",
  "zipCode": "z.string()",
  "city": "z.string()",
  "state": "z.string()",
  "county": "z.string()",
  "number": 43,
  "bulk": 43,
  "rotule": "z.string()",
  "weight": 43,
  "code": "z.string()"
}

###

# @name fetch_orders_from_location
GET  {{baseUrl}}/orders
  ?city=city
  &state=state
  &amount=3
  &page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
