@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{baseUrl}}/sessions/login
Content-Type: application/json

{
  "cpf": "0000000002",
  "password": "123456"
}

###

# @name create_deliveryman
POST {{baseUrl}}/accounts/deliveryman
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "addressId": "d6319d6f-90b7-4374-b52a-245c43b8456a",
  "name": "John Doe",
  "cpf": "00000000003",
  "password": "123456",
  "city": "city example",
  "code": "12345678",
  "complement": "",
  "county": "county example",
  "state": "state example",
  "street": "street example",
  "number": ""
}

###

# @name fetch_orders_from_location
GET  {{baseUrl}}/orders
  ?city=city
  &state=state
  &amount=3
  &page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
